### ISSUE TITLE
Encounter curious problem in training process： TypeError: _find_caller() takes from 0 to 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by kyrie2to11** [shermanlian/swrn#2]
Thanks for opens ource your code, great work ! In training process I encountered this error.
```
Traceback (most recent call last):
  File "run.py", line 83, in <module>
    main(arguments)
  File "run.py", line 74, in main
    learner.train()
  File "/root/autodl-tmp/swrn-main/learner/learner.py", line 212, in train
    logger.info(f'Restore from {self.saver.restore_ckpt}')
  File "/root/autodl-tmp/swrn-main/util/logger.py", line 226, in info
    _get_logger().info(msg, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: _find_caller() takes from 0 to 1 positional arguments but 2 were given`
```
according to  [this]( https://stackoverflow.com/questions/66451483/builtins-typeerror-findcaller-takes-from-1-to-2-positional-arguments-but-3-w ) , I ceased this fault by adding `import logging logging._srcfile = None`  to run.py.  But something happend to the log output like this:
`2023-02-25 18:49:11,816 [MAI VSR:INFO] (unknown file):0: Step 100 train loss: 94.62708282470703`
may be the added code "import logging logging._srcfile = None" caused "...(unknown file)..." output.

So, have you ever met this problem and how to kill it absolutely !  Looking for your reply : )

**Comment by shermanlian** [comment]
Hi!

Sorry I haven't meet this problem before. Will it be solved by just removing the logging setting line?

**Comment by kyrie2to11** [comment]
Thanks for replying:

I will try this method and give feedback.

**Comment by kyrie2to11** [comment]
Thank U, It works! 

I removed `logger.findCaller = _find_caller` in def _get_logger() of util/logger.py to abandon using customed  def _find_caller(), and  the output shows file reference correctly like this: `2023-03-07 10:59:21,181 [MAI VSR:INFO] logger.py:226: Restore from snapshot/ckpt-21`.

I will close it and thanks again.
